# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: CICD GitHub workflow DG

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "Branch to checkout"
        required: true
        type: string
      jobName:
        description: "Change Job Name"
        required: true
        type: string
    secrets:
      SN_DEVOPS_TOKEN:
        description: "ServiceNow DevOps token"
        required: true
      SN_INSTANCE_URL:
        description: "ServiceNow instance URL"
        required: true
      SN_ORCHESTRATION_TOOL_ID:
        description: "ServiceNow orchestration tool id"
        required: true
  
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     cache: maven
    - name: Build with Maven
      run: echo 'Build step in progress...' 

  test:
    name: 'Test'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: ServiceNow DevOps Unit Test Results
        uses: ServiceNow/servicenow-devops-test-report@v6.0.0
        with:
          # Devops Integration Token
          # devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          # devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          # ServiceNow Instance Name
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          # Orchestration Tool Id
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          # Job Name
          job-name: 'Test' 
          # Should be same name as declared in 'name' clause of the current Stage
          test-summary-name: 'Ankur Test Summary'
          # Github Context
          context-github: ${{ toJSON(github) }}
          # JUnit xml report file name with path
          xml-report-filename: testing.xml

  # sonarScan:
  #   name: Sonar Scan
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.1.0
  #     - name: ServiceNow DevOps Sonar Scan Results
  #       uses: ServiceNow/servicenow-devops-sonar@v5.1.0
  #       with:
  #         instance-url: '${{ secrets.SN_INSTANCE_URL }}'
  #         # devops-integration-token: '${{ secrets.SN_DEVOPS_TOKEN }}'
  #         devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
  #         devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
  #         tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
  #         context-github: '${{ toJSON(github) }}'
  #         job-name: Sonar Scan
  #         sonar-host-url: '${{ secrets.SONAR_URL }}'
  #         sonar-project-key: '${{ secrets.SONAR_PROJECT_KEY }}'

  change:
    name: Change Request
    needs: test
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow DevOps Change Attributes
        uses: ServiceNow/servicenow-devops-change@main
        with:
          # devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          # devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Change Request'
          change-request: '{"autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployments","chg_model":"007c4001c343101035ae3f52c1d3aeb2","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed."}}'  
          interval: '100'
          timeout: '3600'
          deployment-gate: '{"environment": "dg_demo", "jobName": "Deploy"}'

  deploy:
    name: 'Deploy'
    needs: change
    runs-on: ubuntu-latest
    environment: dg_demo
    steps:
      - name: Run deployment scripts
        run: echo Completed Deployment
        
  # getchange:
  #   # jobs that  must complete successfully before this job will run
  #   needs: change
  #   # type of machine to run the job on
  #   runs-on: ubuntu-latest
  #   name: 'ServiceNow DevOps Get Change'
  #   outputs:
  #     change-request-number: ${{ steps.get_change.outputs.change-request-number }}
  #   steps:
  #     - name: ServiceNow DevOps Get Change
  #       # You may pin to the exact commit or the version.
  #       # uses: ServiceNow/servicenow-devops-get-change@0f8b1914adeaec764a4286bdd9cba73ed1c6097f
  #       uses: ServiceNow/servicenow-devops-get-change@v5.1.0
  #       id: get_change
  #       with:
  #         # ServiceNow Instance URL
  #         instance-url: ${{ secrets.SN_INSTANCE_URL }}
  #         # Devops Integration Token
  #         devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
  #         # devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
  #         # devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
  #         # Orchestration Tool Id
  #         tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
  #         # Github Context
  #         context-github: ${{ toJSON(github) }}
  #         # The inputs to identify change at Servicenow and GET it.
  #         change-details: '{"build_number":"","pipeline_name":"","stage_name":"Change Request"}'

  #     - name: Output of ServiceNow DevOps Get Change
  #       run: echo 'Output of ServiceNow DevOps Get Change is -> change-request-number = ${{ steps.get_change.outputs.change-request-number }}' >> $GITHUB_OUTPUT

  # updatechange:
  #   # jobs that must complete successfully before this job will run
  #   needs: getchange
  #   # type of machine to run the job on
  #   runs-on: ubuntu-latest
  #   name: 'ServiceNow DevOps Update Change'
  #   steps:
  #     - name: ServiceNow DevOps Update Change
  #       # You may pin to the exact commit or the version.
  #       # uses: ServiceNow/servicenow-devops-update-change@66d51cb13684d8287a763bc3f4dc4531c6ab3306
  #       uses: ServiceNow/servicenow-devops-update-change@v5.1.0
  #       id: update_change
  #       with:
  #         # ServiceNow Instance URL
  #         instance-url: ${{ secrets.SN_INSTANCE_URL }}
  #         # ServiceNow Devops security token
  #         devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
  #         # devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
  #         # devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
  #         # Orchestration Tool Id of the tool created in ServiceNow
  #         tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
  #         # Github Context
  #         context-github: ${{ toJSON(github) }}
  #         # Change Request Number to be Updated
  #         change-request-number: ${{needs.getchange.outputs.change-request-number}}
  #         # The customized inputs to create change with the requested details.
  #         change-request-details: '{"short_description": "Test description in Updated by Github custom Action","description":"Automated Software Deployment.","close_code":"successful", "close_notes":"Closing during Github Actions CustomActionUpdate","state":"3"}'
  #     # - name: Outcome of ServiceNow DevOps Update Change
  #     #   run: echo 'Outcome of ServiceNow DevOps Update Change is -> ${{ steps.update_change.outputs.status }}'  >> $GITHUB_OUTPUT 
